# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='cname',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
